name: 'Setup Python Environment'
description: 'Sets up Python and installs dependencies'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/uv
          ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('src/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install uv
      run: pip install uv
      shell: bash

    - name: Install dependencies
      shell: bash
      run: |
        cd src
        uv sync --frozen

    - name: Install pytest-cov
      shell: bash
      run: uv add pytest-cov --dev
