version: '3.8'
name: theary

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: theary_django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    env_file:
      - ./.env
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: theary_postgres_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
