[project]
name = "theary-coding-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
    "dotenv>=0.9.9",
    "pydantic>=2.11.5",
    "pydantic-settings>=2.9.1",
    "structlog>=25.3.0",
]
