# Generated by Django 5.2.1 on 2025-05-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TreeNode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label for the tree node",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the node was created",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent node reference (null for root nodes)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="tree.treenode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tree Node",
                "verbose_name_plural": "Tree Nodes",
                "db_table": "tree_node",
                "ordering": ["id"],
            },
        ),
    ]
