name: Theary CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup
      - name: Run Security Checks
        uses: ./.github/actions/security-checks

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup
      - name: Run Linting
        uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest
    environment: test
    needs: [security, lint]
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: ${{ vars.DB_NAME }}
          POSTGRES_USER: ${{ vars.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python Environment
      uses: ./.github/actions/setup

    - name: Run Tests
      uses: ./.github/actions/test
      with:
        db_host: localhost
        db_port: 5432
        db_name: ${{ vars.DB_NAME }}
        db_user: ${{ vars.DB_USER }}
        db_password: ${{ secrets.DB_PASSWORD }}
        secret_key: ${{ secrets.SECRET_KEY }}
