name: Theary CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup
      - name: Run Security Checks
        uses: ./.github/actions/security-checks

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup
      - name: Run Linting
        uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest
    needs: [security, lint]

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python Environment
      uses: ./.github/actions/setup

    - name: Run Tests
      uses: ./.github/actions/test

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: src/test-results.xml
